apiVersion: v1
publisher: hellofalks
name: hellofalks
version: 0.0.1
type: VS Code extension
displayName:
title:
description:
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository:
category:
spec:
  containers:
    - image:
      memoryLimit:
      memoryRequest:
      cpuLimit:
      cpuRequest:
  extensions:
          - https://github.com/william-xiang/vs-extension/raw/main/helloFalks.vsix